on: push
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
 #   - name: ðŸšš Get latest code
 #     uses: actions/checkout@v3
    
    - name: ðŸ“‚ Sync files
      uses: actions/checkout@v3
      with:
        server: 51.178.44.177
        username: root
        password: 7"KKh=f4X$~(46="&BHGFFgd{LSX
        server-dir: /var/www/html/